### PR TITLE
Groupdupes

### PR DESCRIPTION
**Pull request by krisfield**
Add script to delete duplicate files and leave breadcrumb file in their place. Script keeps most recently accessed file.

### CODE REVIEW

**Comment by jamesmontalvo3** [comment]
I just skimmed the code so far...am I understanding it right that duplicate files are removed (except one of them) and the rest are logged in a common log file. What about dropping a shortcut with the original filename from the deleted location to the kept location?

**Comment by krisfield** [comment]
Ya that's generally correct. The most recently accessed file is the one kept out of any given set of duplicates. The script does not drop a shortcut to the remaining file but it leaves a txt file with the name of the file removed and the path to the remaining instance of that file. I don't think creating individual shortcuts to every file will really cleanup a directory. There is only one text file create for each directory. If there is more than one deleted file in a directory then it's info will just be appended to the text file.

**Comment by krisfield** [comment]
closing this request to merge further upstream

**Comment by jamesmontalvo3** [comment]
Not sure I understand why you closed this. The new PR (#9) appears to have the same content.

**Pull request closed without merging**
